local builtin = require('telescope.builtin')
local actions = require('telescope.actions')
local telescope = require("telescope")
vim.keymap.set("n", "<C-p>", ":find ", { desc = "Find files (works with :set path=**)" })
-- vim.keymap.set("n", "<leader>p0", ":grep -R ", { desc = "Search files" })
-- vim.keymap.set("n", "<C-p>", ":find **/", { desc = "Find files" })
