-- local wk = require("which-key")

-- wk.register({
--   a = {
--     "Add to harpoon"
--   },
--   hd = {
--     "Diff this"
--   },
--   tb = {
--     "Git blame"
--   },
-- }, { prefix = "<leader>" })

-- wk.register({
--   name = "hard coded macros",
--   e = {
--     name = "className={} toggle `${}`",
--     e = {},
--     d = {},
--   },
--   s = {
--     name = "case toggle",
--     s = {  },
--   }
-- }, { prefix = "-" })
